### ISSUE TITLE
section 12.3 RegExp.lastMatch / RegExp["$&"]  is blank

### ISSUE THREAD

**Issue by cvrebert** [whatwg/javascript#14]
<http://javascript.spec.whatwg.org/#regexp.lastmatch>

It doesn't even have a `TODO` like the `Function.prototype.toString()` section does.

**Comment by domenic** [comment]
This is gone from the latest draft per https://github.com/whatwg/javascript/commit/e90cc074dad3d40b20b23ebe699ae586a2d3fca4 so closing.
