### ISSUE TITLE
`08` parses

### ISSUE THREAD

**Issue by Hixie** [whatwg/javascript#17]
As far as I can tell, `08` doesn’t parse per the ES spec, but it does parse in Chrome and Firefox (as a decimal literal).

**Comment by mathiasbynens** [comment]
https://bugs.ecmascript.org/show_bug.cgi?id=2792#c11

**Comment by domenic** [comment]
Per https://bugs.ecmascript.org/show_bug.cgi?id=2792#c11 this has been fixed upstream; closing.
