### ISSUE TITLE
Add `RegExp.$_`, `RegExp.input`, `RegExp['$*']`, and `RegExp.multiline`

### ISSUE THREAD

**Issue by phistuck** [whatwg/javascript#22]
They contain the source string used for the last regular expression matching.

`RegExp.input` is a [Microsoft extension](http://msdn.microsoft.com/en-us/library/ff520815(v=vs.85).aspx), and it is just an alias for `RegExp.$_`. It is also supported in Chrome/Opera (V8) (I have not tried other browsers).

```
var str = "something";
str.match(/(eth)/);
RegExp.$_ // something
RegExp.input // something
```

**Comment by domenic** [comment]
It seems like the decision in https://github.com/whatwg/javascript/commit/e90cc074dad3d40b20b23ebe699ae586a2d3fca4 has been to delegate to https://github.com/claudepache/es-regexp-legacy-static-properties instead, so I'll close this. I did open https://github.com/claudepache/es-regexp-legacy-static-properties/issues/12 based on the contents of this bug though.
