### ISSUE TITLE
`String.prototype.{trimLeft,trimRight}`

### ISSUE THREAD

**Issue by mathiasbynens** [whatwg/javascript#23]

**Comment by mathiasbynens** [comment]
https://esdiscuss.org/topic/string-prototype-trimright-trimleft Looks like @DmitrySoshnikov will do the leg work here. Leaving this issue open until that happens.

**Comment by DmitrySoshnikov** [comment]
This now was approved on the recent meeting.

**Comment by mathiasbynens** [comment]
Spec: https://gist.github.com/DmitrySoshnikov/65a2070477fffb465048
Discussion: https://esdiscuss.org/topic/string-prototype-trimright-trimleft#content-6
