### ISSUE TITLE
Should unhandled Promise rejections trigger an "error" event?

### ISSUE THREAD

**Issue by caitp** [whatwg/javascript#24]
Currently, [Chromium/Blink logs a warning to the console](https://chromium.googlesource.com/chromium/blink/+/7cfccdd6ae324eb3998ccb683969f39f0c6b15f4/Source/bindings/core/v8/RejectedPromises.cpp#75) when it determines a promise rejection to be uncaught --- this is pretty friendly for developers (and it would be awesome if this was Annex B-ified or something) --- But it would also probably be nice to emit an "error" event so that `window.onerror` on the UI thread could handle this, and fit in better with the general "global" error handler.

I'm not sure if people have discussed this much or not, since Blink seems to be the only one doing this (logging) at the moment --- but it would be real nice if we could get implementations on the same page, and maybe do a bit more

**Comment by caitp** [comment]
I guess this is sort of covered at https://github.com/domenic/unhandled-rejections-browser-spec

**Comment by domenic** [comment]
Yep. That's advancing for a patch to the ES spec and the HTML specs as it gains acceptance from other vendors. Hope you're OK with me closing?
