### ISSUE TITLE
Update for ES2015

### ISSUE THREAD

**Issue by domenic** [whatwg/javascript#25]
They incorporated less than we thought, but I think they got comments. The errata is incorporated.

IMO having sections for IsCallable etc. is not that necessary. Just make them hyperlinks where they appear.

Probably should use http://www.ecma-international.org/ecma-262/6.0/

**Comment by domenic** [comment]
Should probably use https://tc39.github.io/ecma262/ instead

**Comment by domenic** [comment]
More:

- [ ] https://javascript.spec.whatwg.org/#top-level-var-statements is no longer necessary
- [ ] All of Annex B should be required, not just Octal escapes in https://javascript.spec.whatwg.org/#octal-escapes-in-regular-expression-literals

**Comment by mathiasbynens** [comment]
>  https://javascript.spec.whatwg.org/#octal-escapes-in-regular-expression-literals is no longer necessary, since all of Annex B is required per https://javascript.spec.whatwg.org/#annex-b

http://ecma-international.org/ecma-262/6.0/#sec-additional-syntax-string-literals (or https://tc39.github.io/ecma262/#sec-additional-syntax-string-literals B.1.2 for that matter) only mentions string literals, not [regular expression literals](https://tc39.github.io/ecma262/#sec-literals-regular-expression-literals). Am I misreading the spec?

**Comment by domenic** [comment]
It should be taken care of by https://tc39.github.io/ecma262/#sec-regular-expressions-patterns, which adds LegacyOctalEscapeSequence to CharacterEscape.

**Comment by mathiasbynens** [comment]
@domenic That (currently) only happens in sloppy mode, though:

 > A conforming implementation, when processing **strict mode code** (see 10.2.1), must not extend the syntax of `EscapeSequence` to include `LegacyOctalEscapeSequence` as described in B.1.2.

https://javascript.spec.whatwg.org/#octal-escapes-in-regular-expression-literals mentions strict mode specifically.

**Comment by domenic** [comment]
That doesn't impact B.1.4 on regexps though.

**Comment by domenic** [comment]
I think we're fully updated now, as of some recent commits.
