### ISSUE TITLE
ToHTML and EscapeAttributeValue are dead code

### ISSUE THREAD

**Issue by domenic** [whatwg/javascript#27]
Since those moved into the ES spec the abstract operation definition here is not used anymore

**Comment by domenic** [comment]
This appears to have been removed in https://github.com/whatwg/javascript/commit/6ce920de33027dc1b83fdfaa9ade18c1283d91f0 but the spec not updated, hmm.

**Comment by mathiasbynens** [comment]
Not sure what happened there, but https://javascript.spec.whatwg.org/ is up-to-date now.
