### ISSUE TITLE
Remove Unicode version requirement

### ISSUE THREAD

**Issue by littledan** [whatwg/javascript#28]
In TC39, we came to consensus on requiring Unicode 8.0.0 for ES2016, and it seemed to me like future ECMAScript versions would require the current Unicode version at the time. I don't think the JavaScript spec needs to require these additional things.

**Comment by mathiasbynens** [comment]
Relevant discussion:

https://github.com/rwaldron/tc39-notes/blob/master/es7/2016-01/2016-01-26.md#unicode-fix-httpsgithubcomtc39ecma262pull300-de
https://github.com/tc39/ecma262/pull/300
https://bugs.ecmascript.org/show_bug.cgi?id=2071

As always, I’ll happily remove this from the JavaScript spec as soon as it lands in the ECMAScript spec (i.e. when https://github.com/tc39/ecma262/pull/300 gets merged).

**Comment by littledan** [comment]
+1! An additional suggestion--so that you don't have to update those number-based references, why not just refer to ids in the current ECMAScript draft spec? These are more stable.

**Comment by mathiasbynens** [comment]
The number-based references were added back when there were no text-based IDs available in [the generated HTML version of the spec](https://people.mozilla.org/~jorendorff/es6-draft.html). It would make sense to update them but then again I’m hoping the JavaScript spec can soon be obsoleted/removed.
