### ISSUE TITLE
Spec `Function.prototype.toString`

### ISSUE THREAD

**Issue by mathiasbynens** [whatwg/javascript#3]
ES6 will probably spec it, though:
http://wiki.ecmascript.org/doku.php?id=harmony:function_to_string
http://wiki.ecmascript.org/doku.php?id=strawman:function_to_string
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-function.prototype.tostring

**Comment by domenic** [comment]
It looks like per https://github.com/whatwg/javascript/commit/3cf475449d729ad0fb3b88819d9add2113736684 we should close this since this spec no longer defines it.
