### ISSUE TITLE
Remove Date.UTC after tc39/ecma262#642 is merged

### ISSUE THREAD

**Issue by evilpie** [whatwg/javascript#31]
Maybe I am wrong, but I tried to follow to spec along here. (https://tc39.github.io/ecma262/#sec-date.utc)

For zero arguments:
_Date.UTC_
1. y = ToNumber(year) => y = NaN
8. This step is somewhat confusing, but we should end up with yr = y = NaN
_MakeDay(yr, m, dt)_
1. Return NaN, yr is not finite.
_MakeDate_
1. Return NaN, day is not finite
_TimeClip_
1. Return NaN, time is not finite

For one argument MakeDay should also return NaN, because month is not finite, so the rest follows.

**Comment by claudepache** [comment]
You just missed the very beginning of the section you pointed to:
> When the UTC function is called with fewer than two arguments, the behaviour is implementation-dependent. When the UTC function is called with two to seven arguments, ...

**Comment by claudepache** [comment]
According to my tests, in general, Chakra does *not* always return NaN when is called with less than two arguments. More precisely, it seems to implement the following variation of the [Date.UTC algorithm](https://tc39.github.io/ecma262/#sec-date.utc):

1. If _year_ is supplied, let _y_ be ? ToNumber(_year_); else let _y_ be 0.
1. If _month_ is supplied, let _m_ be ? ToNumber(_month_); else let _m_ be 0.
1. etc.

which is observable only when less than two arguments are provided.

**Comment by mathiasbynens** [comment]
It would be nice to get implementations to agree on what should happen when `Date.UTC` is called with fewer than two arguments, and to remove this from the ECMAScript spec:

> When the UTC function is called with fewer than two arguments, the behaviour is implementation-dependent.

**Comment by littledan** [comment]
@bterlson What are your thoughts here?

**Comment by bterlson** [comment]
As usual I agree with @mathiasbynens about what would be nice. I can't imagine that this is important for compat scenarios (certainly not missing year, though I could possibly imagine missing month). I'll open a bug on ChakraCore to align with the others here.

**Comment by domenic** [comment]
Let's repurpose this bug to remove the JavaScript Standard's line about Date.UTC once https://github.com/tc39/ecma262/pull/642 is merged.

**Comment by domenic** [comment]
Oh, nevermind, I guess this was already removed in https://github.com/whatwg/javascript/commit/750a6d7fc5310b752c00deb4f37d4308abc70f3c.

**Comment by littledan** [comment]
Well, we still don't have consensus on TC39 to standardize returning NaN for Date.UTC with one argument. It would seem nice to write it down somewhere that that returns NaN.

**Comment by dilijev** [comment]
@littledan Is it worth implementing 0 args returning NaN while we wait for consensus on the 1 argument option, or is a decision forthcoming?

**Comment by littledan** [comment]
From an implementor's point or view, I think it would be fine to ship the consensus from other browsers (0 or 1 arguments returns NaN) to maximize compatibility even if the committee allows something more general.

**Comment by littledan** [comment]
We have no guarantee when a further decision on Date.UTC will come FWIW. It may be a while.
