### ISSUE TITLE
Mention code of conduct in README

### ISSUE THREAD

**Issue by annevk** [whatwg/javascript#32]
See other repositories, such as Fetch or HTML, for an example.

**Comment by RichardMaher** [comment]
I'll start you off with some unwritten rules from the W3C: -

1) All participants must own at least one cat and several "Land Rights for Gay Whales" T-shirts.
2) Anyone who's ever voted conservative or who doesn't regularly bear witness to the loony left via their Twitter account is to be shunned and black-balled.
3) Censorship and revisionism is positively encouraged when dealing with incorrect thinkers. Closing and Deleting "offensive" posts is your duty.
4) An "offensive" post is one where one or more of our bolshie self-serving star-chamber of social rejects finds the tone inapropos  or lacking the necessary decorum expected of a bunch of pretentious knobs.

Well, that's just been my experience. YMMV.
