### ISSUE TITLE
Consider pointing to in-progress proposals that document web reality

### ISSUE THREAD

**Issue by domenic** [whatwg/javascript#36]
So far I know of:

- https://github.com/sebmarkbage/ecmascript-string-left-right-trim
- https://github.com/tc39/Function-prototype-toString-revision
- https://github.com/claudepache/es-regexp-legacy-static-properties
- Some in-progress proposal from @erights and @ljharb on Error.prototype.stack; is that online somewhere?

There are also a number of important open bugs, which I've tagged as ["web reality"](https://github.com/tc39/ecma262/labels/web%20reality) on the TC39 repo.

**Comment by ljharb** [comment]
No, it'll be `System.getStack`, and I hope to have something written up before September.

There's also https://github.com/claudepache/es-regexp-legacy-static-properties as well.

**Comment by domenic** [comment]
I mean, we also need to have an Error.prototype.stack getter for web compatibility (annex B it if that makes you feel better). @erights seems to agree on that point last we talked.

**Comment by ljharb** [comment]
Oh, right, that's true. I'll make sure that's included in the writeup.

**Comment by mathiasbynens** [comment]
https://github.com/tc39/ecma262/issues/663
https://github.com/tc39/ecma262/issues/664
https://github.com/tc39/ecma262/issues/665

Can someone please tag those issues with the “web reality” label?

Closing this issue in favor of #29.
