### ISSUE TITLE
Jeff Walden isn’t interested in “standardizing” non-standard features

### ISSUE THREAD

**Issue by vyv03354** [whatwg/javascript#6]
See https://bugzilla.mozilla.org/show_bug.cgi?id=815013
and https://bugzilla.mozilla.org/show_bug.cgi?id=815014

**Comment by domenic** [comment]
This seems to have been fixed in modern JavaScript, according to https://bugs.ecmascript.org/show_bug.cgi?id=157, so I'll close this...

**Comment by domenic** [comment]
Oops, wrong bug. While I think this is probably closable as well, I'll reopen it for now.

**Comment by domenic** [comment]
OK, well, now that I've done all the bug triage on this repo, I want to close this one too. I think there's broad consensus to standardize all implemented things, with the possible exception of function.arguments.
