### ISSUE TITLE
JavaScript spec should mention the semicolon insertion after do-while

### ISSUE THREAD

**Issue by vyv03354** [whatwg/javascript#8]
See 
https://bugzilla.mozilla.org/show_bug.cgi?id=238945
https://code.google.com/p/v8/issues/detail?id=1127
https://bugs.ecmascript.org/show_bug.cgi?id=8

**Comment by domenic** [comment]
This seems to have been fixed in modern JavaScript, according to https://bugs.ecmascript.org/show_bug.cgi?id=157, so I'll close this...
